apiVersion: v1
kind: Secret
metadata:
  name:  security-monkey
data:
   postgres-uri:  BASE64_ENCODED_VALUE
   secret-key:  BASE64_ENCODED_VALUE
   secret-password-salt:  BASE64_ENCODED_VALUE
type: Opaque